# Generated by Django 5.1.6 on 2025-03-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Test name')),
                ('test_text', models.CharField(db_column='test text')),
            ],
        ),
    ]
