# Generated by Django 5.1.6 on 2025-03-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(db_column='Test name'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='test_text',
            field=models.TextField(db_column='test text'),
        ),
    ]
