# Generated by Django 5.1.6 on 2025-03-17 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testmodel_name_alter_testmodel_test_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppartmentsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Appartment name')),
                ('address', models.CharField(db_column='Appartment address')),
                ('description', models.TextField(db_column='Appartment description')),
                ('extra_desc', models.TextField(db_column='Additional description', default='')),
            ],
        ),
        migrations.CreateModel(
            name='AppartmentsPhotosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/appartments_images/')),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.appartmentsmodel')),
            ],
        ),
    ]
