# Generated by Django 5.1.6 on 2025-03-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appartmentsmodel_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartmentsmodel',
            name='city',
            field=models.CharField(db_column='City', default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appartmentsmodel',
            name='extra_desc',
            field=models.TextField(blank=True, db_column='Additional description', default=''),
        ),
        migrations.AlterField(
            model_name='appartmentsphotosmodel',
            name='image',
            field=models.ImageField(upload_to='appartments_images/'),
        ),
    ]
