# Generated by Django 5.1.6 on 2025-04-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepagecounters_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartmentsmodel',
            name='description',
            field=models.TextField(blank=True, db_column='Appartment description', default=''),
        ),
        migrations.AlterField(
            model_name='appartmentsmodel',
            name='extra_desc',
            field=models.TextField(blank=True, db_column='Appartment features', default=''),
        ),
    ]
