# Generated by Django 5.1.6 on 2025-04-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appartmentsmodel_extra_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartmentsmodel',
            name='extra_desc',
            field=models.TextField(db_column='Additional description', default=''),
        ),
    ]
